name: Dependabot

on:
  pull_request_target:
  workflow_dispatch:

permissions: read-all

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' && contains( github.head_ref, 'npm_and_yarn' ) }}

    permissions:
      pull-requests: write
      contents: write

    strategy:
      matrix:
        node-version: [ 17.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: ^7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3.2.4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update lock file
        run: pnpm i --lockfile-only

      - name: Push the updated lock file
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add pnpm-lock.yaml
          git commit -m 'chore(deps): update the `pnpm` lock file'
          git push
